import { Product } from './modules/product/models/product.model';

export const PRODUCTS: Product[] = [
  {
    id: 0,
    name: 'Sản phẩm A',
    price: 11,
    rating: 2,
    category: 'rau',
  },
  {
    id: 1,
    name: 'Sản phẩm B',
    price: 12,
    rating: 3,
    category: 'trai_cay',
  },
  {
    id: 2,
    name: 'Sản phẩm C',
    price: 13,
    rating: 4,
    category: 'thit',
  },
  {
    id: 3,
    name: 'Sản phẩm D',
    price: 14,
    rating: 4,
    category: 'rau',
  },
  {
    id: 4,
    name: 'Sản phẩm E',
    price: 15,
    rating: 3,
    category: 'trai_cay',
  },
  {
    id: 5,
    name: 'Sản phẩm F',
    price: 16,
    rating: 2,
    category: 'thit',
  },
  {
    id: 6,
    name: 'Sản phẩm G',
    price: 17,
    rating: 2,
    category: 'rau',
  },
  {
    id: 7,
    name: 'Sản phẩm H',
    price: 18,
    rating: 3,
    category: 'trai_cay',
  },
  {
    id: 8,
    name: 'Sản phẩm I',
    price: 19,
    rating: 4,
    category: 'thit',
  },
  {
    id: 9,
    name: 'Sản phẩm J',
    price: 20,
    rating: 4,
    category: 'rau',
  },
  {
    id: 10,
    name: 'Sản phẩm K',
    price: 21,
    rating: 3,
    category: 'trai_cay',
  },
  {
    id: 11,
    name: 'Sản phẩm L',
    price: 22,
    rating: 2,
    category: 'thit',
  },
];
